package-lock.json
package.json
server/app.ts
server/controllers/index.ts
server/controllers/searchEformController.test.ts
server/controllers/searchEformController.ts
server/errorHandler.test.ts
server/routes/index.test.ts
server/routes/index.ts
server/routes/testutils/appSetup.ts
server/services/index.ts
server/services/searchEformService.test.ts
server/services/searchEformService.ts
server/views/pages/searchEform.njk

This PR is about: 
- Displaying the results after triggering the search button of the `Search Historical eForm` page
- It also includes some structural refactoring to MVC model
- It also includes some readjustment of tests

EMP-196: Display searchAPI results - Part 1

---

package-lock.json
package.json
server/controllers/searchEformController.test.ts
server/errorHandler.test.ts
server/routes/index.test.ts
server/routes/testutils/appSetup.ts
server/services/searchEformService.test.ts

Fixed controller and routes unit tests.

EMP-239:  Clean up tests

---

.github/workflows/action.yml

Added main branch  set as deployment branch

Added main branch  set as deployment branch

---

Dockerfile

All varibales commented to revisit later if needed.

Update Dockerfile to remove varibale

---

.github/deployments/ingress.yml

EMP-000: using default as ingress class name

EMP-000: using default as ingress class name

---

server/@types/searchEform/index.d.ts
server/controllers/searchEformController.test.ts
server/controllers/searchEformController.ts
server/data/searchApiClient.test.ts
server/routes/index.test.ts
server/services/searchEformService.test.ts
server/utils/searchEformValidation.test.ts
server/utils/searchEformValidation.ts
server/views/components/searchEformBox.njk
server/views/pages/searchEform.njk

- Added status to search results type
- Updated search eform template to return status field
- Empty search form validation fix and test

Add search results status

---

server/controllers/crm5Controller.test.ts
server/controllers/crm5Controller.ts
server/controllers/index.ts
server/routes/index.test.ts
server/services/index.ts
server/services/json/crm5NavigationConfig.json
server/services/navigationService.test.ts
server/services/navigationService.ts

https://dsdmoj.atlassian.net/browse/EMP-284
- Create logic to display the left navigation bar
`NavConfig.json` > `NavService.ts` > `crm5Controller.ts` > `index.ts` (x2)
- Adapt tests to includes navigation on page

EMP-284: CRM5 - Navigation bar configuration - Part 2

---

server/views/pages/searchEform.njk

https://dsdmoj.atlassian.net/browse/EMP-285
- This PR set the status colours on the result page

EMP-285: Status styling

---

.github/deployments/deployment.yml
package-lock.json
package.json
server/@types/express/index.d.ts
server/auth/authConfig.ts
server/auth/authProvider.ts
server/routes/index.ts
tsconfig.json

Reverts ministryofjustice/laa-crime-equinity-historical-data-frontend#121

POC: SSO using msal-node library

---

server/services/config/crm5DisplayConfig.json
server/services/config/crm5NavigationConfig.json
server/services/navigationService.test.ts

- Added Proceedings, Statement of Case to the navigation and display configuration.
- Added LAA Advice Assistantance to display config.

EMP-262: (Part 3) Add missing sections

---

server/views/components/searchEformBox.njk

- Minor change on dropdown naming following QA test

EMP-244: Dropdown text for CRM14/15

---

server/@types/crm4/index.d.ts
server/@types/crm5/index.d.ts
server/@types/crmDisplay/index.d.ts
server/@types/eqApi/index.d.ts
server/controllers/crm/crm5Controller.ts
server/data/api/crmApiClient.ts
server/services/config/crm5DisplayConfig.json
server/services/crmApiService.ts
server/services/crmDisplayService.test.ts
server/services/crmDisplayService.ts

- Added common interface CrmResponse
- Added displayWhen field to section in config file
- Added conditions 1.1, 2.1., 3.1 (1.2 to be done in Part 2, awaiting BE fix)
- Modified CrmDisplayService to check section.displayWhen for getCrmNavigation() & getSection()
- Added unit test cases for each CRM 5 display condition

EMP-291: CRM5 Display conditional sections (Part 1)

---

server/utils/crmFieldFormatter.test.ts
server/utils/crmFieldFormatter.ts

**Changes made**
- Format date with month name

EMP-210: Updated date format

---

server/@types/crm5/index.d.ts
server/@types/crmDisplay/index.d.ts
server/services/config/crm5DisplayConfig.json
server/services/crmDisplayService.test.ts
server/services/crmDisplayService.ts
server/utils/crmDisplayConfigValidation.ts

- Added cwCriminalProceeding to CaseDetails type
- Replaced displayWhen with ShowWhen and HideWhen types
- Modified display configuration to use showWhen & hideWhen conditions where required
- Updated CRM Display service to check for showWhen & hideWhen conditions 
- Updated schema for CRM display configuration

EMP-291:  Display conditional sections (Part 2)

---

server/controllers/crm/crm4Controller.test.ts
server/controllers/crm/crm4Controller.ts
server/controllers/crm/crm5Controller.test.ts
server/routes/index.test.ts
server/services/config/crm4DisplayConfig.json
server/services/crmDisplayService.ts
server/views/components/formField.njk

- Created CRM4 display configuration file
- Modified display service to read CRM4 config
- Modified CRM4 controller to pass data to view
- Updated tests

EMP-296: CRM4 - Full page display configuration

---

server/services/crmDisplayService.ts

- Modified crmDisplayService to prefix all apiFieldName with `formDetails`.

EMP-341: Fix CRM 4 UI to support new CRM 4 API structure

---

server/@types/crm4/index.d.ts
server/@types/crm7/index.d.ts
server/@types/crmDisplay/index.d.ts
server/controllers/crm/crm7Controller.test.ts
server/controllers/crm/crm7Controller.ts
server/controllers/crm/index.ts
server/data/api/crmApiClient.ts
server/data/index.ts
server/routes/index.test.ts
server/routes/index.ts
server/services/crmDisplayService.ts
server/services/index.ts
server/services/searchEformService.ts
tsconfig.json

Changes made:
- Created CRM7 types
- Created CRM7 controller and test
- Created CRM7 API client
- Created CRM7 service
- Added crm7 route

EMP-354: Set up CRM7 controller

---

server/controllers/crm/crm4Controller.test.ts
server/controllers/crm/crm5Controller.test.ts

BAU: Fix types in test

---

server/services/config/crm4DisplayConfig.json
server/views/components/customDisplay/crm4/crm4AlternativeQuotes.njk

- Fixed field format in Alternative Quotes
- Added missing Firm DX field
- Added missing Details of Proceedings fields

EMP-339: UI fixes for CRM4 Alternative Quotes

---

assets/scss/local.scss
server/views/components/formField.njk
server/views/components/timeAndCost.njk
server/views/components/totalAndCost.njk
server/views/pages/crmDetails.njk

changes to following views - 
- crmDetails.njk
- formField.njk
- timeAndCost.njk
- totalAndCost.njk

EMP-342: made layout and styling changes to crm views-

---

assets/scss/components/_custom-display-table.scss
assets/scss/components/all.scss
server/views/components/customDisplay/crm4/crm4AdditionalExpenditure.njk
server/views/components/formSubsection.njk

changes
- created new attributes for table row data in crm4AdditionalExpenditure.njk
- amended formSubsection.njk view
- created custom-display-table.scss with new styles to collapse table in mobile view

EMP-349  FE <Feature> : Fix styling for custom display - table data display

---

.gitignore
README.md
docker-compose-test.yml
docker-compose.yml
server/app.ts
server/config.ts

**Gotenberg Docker setup**
Added `Gotenberg` docket setup in both `docker-compose.yml` & `docker-compose-test.yml`
Updated configs in both `app.ts` and `config.ts`
Updated `README.md` dependencies section

EMP-340 - Gotenberg Docker setup

---

server/config.ts

Reverting `config.ts` changes to fix the Build failures

EMP-340 - Reverting config.ts changes

---

server/services/config/crm7DisplayConfig.json
server/views/components/customDisplay/crm7/crm7CaseDisposal.njk
server/views/components/customDisplay/customDisplay.njk

Changes
- amended crm7DisplayCongig.json
- created crm7CaseDisposal.njk
- amended customDisplay.njk

EMP-364  CRM7 - Complex page => Case Disposal

---

server/controllers/crm/crm4Controller.ts
server/controllers/crm/crm5Controller.ts
server/controllers/downloadEvidenceController.test.ts
server/controllers/downloadEvidenceController.ts
server/data/api/sdsApiClient.ts
server/services/downloadEvidenceService.ts
server/views/components/customDisplay/crmEvidence.njk
server/views/components/formField.njk

- Modified downloadEvidenceController to rename the file to be downloaded.
- Updated tests

EMP-331:  Rename downloaded evidence file name

---

.github/deployments/deployment.yml

Changes made:-
Add SSO_ENABLED env var to deployment.yml

EMP-385: Add missing SSO env var

---

server/routes/index.ts

Removed redirect to auth endpoint

EMP-385: Remove root path redirect to auth endpoint

---

.github/deployments/deployment.yml
server/routes/index.ts

- Added REDIS_AUTH_TOKEN env var to deployment.yml.

EMP-385: Add REDIS_AUTH_TOKEN env var

---

.github/deployments/deployment.yml

Changes made:
Disable redis in deployment.yml.

EMP-385: Temporarily disable redis

---

server/@types/crm14/index.d.ts
server/@types/crm4/index.d.ts
server/@types/crm5/index.d.ts
server/@types/crm7/index.d.ts
server/@types/eqApi/index.d.ts
server/controllers/crm/crm14Controller.test.ts
server/controllers/crm/crm14Controller.ts
server/controllers/crm/crm4Controller.test.ts
server/controllers/crm/crm5Controller.test.ts
server/controllers/crm/crm7Controller.test.ts
server/controllers/crm/index.ts
server/data/api/crmApiClient.test.ts
server/data/api/crmApiClient.ts
server/data/index.ts
server/routes/index.test.ts
server/routes/index.ts
server/services/crmApiService.test.ts
server/services/crmDisplayService.test.ts
server/services/index.ts
server/services/searchEformService.ts
server/views/components/searchEformBox.njk
tsconfig.json

- Added CRM14Response type
- Added CRM14 Controller
- Added crm14 route
- Added unit tests

EMP-370: Set up CRM14 controller

---

.github/deployments/deployment.yml

Changes made:
Add REDIS_TLS_ENABLED to deployment.yml

EMP-385: Set REDIS_TLS_ENABLED environment variable

---

server/services/config/crm7DisplayConfig.json
server/utils/crmFieldFormatter.ts
server/utils/nunjucksSetup.ts
server/views/components/customDisplay/crm7/crm7ClaimForCosts.njk
server/views/components/customDisplay/customDisplay.njk
server/views/components/formField.njk
server/views/components/formSubsection.njk

Changes - 
- created crm7ClaimForCosts.njk
- updated crm7DisplayConfig.json
- added format filter for percentages to crmFieldFormatter.ts 
- added crm7ClaimForCosts.njk to customDisplay.njk
- adjusted formSubsection to deal with table format for crm7ClaimForCosts.njk 
- added percentage filter to nunjucksSetup.ts

EMP-366   CRM7 - Complex page => Claim for Costs

---

docker-compose.yml
server/@types/express/index.d.ts
server/data/redisClient.ts

- Additional redis client logging
- Change redis version to 7.0 in docker compose

EMP-385: Additional redis client logging

---

server/utils/userProfileGroups.ts

Change mades:
Add logging to userProfileGroups

EMP-388: additional logging

---

server/auth/authConfig.ts
server/config.ts

- Set 'azure/msal-node' log level to INFO, currently VERBOSE.
- Add REDIRECT_URI, POST_LOGOUT_REDIRECT_URI to config.

FIX: Set sso logging level to INFO

---

server/views/components/customDisplay/crm7/crm7ClaimForCosts.njk
server/views/components/formSubsection.njk
server/views/components/formTable.njk

changes - 
-amended formTable.njk tyo include table that was in formSubsection.njk
- removed table from formSubsection.njk
- small amendment in crm7ClaimForCosts.njk

Emp 401 fe feature fix styling for crm 14 interests of justice 1

---

server/@types/crmDisplay/index.d.ts
server/controllers/crm/crm14Controller.test.ts
server/controllers/crm/crm14Controller.ts
server/controllers/crm/crm4Controller.test.ts
server/controllers/crm/crm4Controller.ts
server/controllers/crm/crm5Controller.test.ts
server/controllers/crm/crm5Controller.ts
server/controllers/crm/crm7Controller.test.ts
server/controllers/crm/crm7Controller.ts
server/routes/index.test.ts
server/services/config/crm14DisplayConfig.json
server/services/config/crm4DisplayConfig.json
server/services/config/crm5DisplayConfig.json
server/services/config/crm7DisplayConfig.json
server/services/crmDisplayService.test.ts
server/services/crmDisplayService.ts
server/utils/crmDisplayConfigValidation.test.ts
server/utils/crmDisplayConfigValidation.ts
server/views/pages/crmDetails.njk

Changes made:
- Added summary section to the crm display config files
- Modified crmDisplayService to return all sections for summary section
- Modified schema validation to allow empty subsections array
- Modified crmDetails macro to loop through sections array

EMP-358: Add CRM Summary section

---

server/services/config/crm14DisplayConfig.json
server/views/components/customDisplay/crm14/crm14AboutTheInformation.njk
server/views/components/customDisplay/crm14/crm14Declarations.njk
server/views/components/customDisplay/customDisplay.njk

Changes - 
- amended crm14AboutTheInformation.njk
- created crm14Declarations.njk
- amended crm14DisplayConfig.json to include crm14Declarations.njk amended customDisplay.njk to include crm14Declarations.njk

EMP-395-crm-14-complex-page-declarations

---

.github/deployments/print_pdf/ingress.yml

EMP-000: Try updating print-pdf (gotemberg) ingress to use same host but with bespoke path

EMP-000: Try updating print-pdf (gotemberg) ingress to use same host but with bespoke path

---

.github/deployments/deployment.yml
server/config.ts
server/controllers/index.ts
server/controllers/printEformController.ts
server/data/api/printApiClient.ts
server/data/index.ts
server/data/restClient.ts
server/routes/index.ts
server/services/index.ts
server/services/printEformService.ts
server/views/pages/crmDetails.njk

Changes made:
Temporary changes to be deployed to dev for POC.

POC: Print Eform

---

server/services/config/crm14DisplayConfig.json
server/views/components/customDisplay/crm14/crm14PrivacyNotice.njk
server/views/components/customDisplay/customDisplay.njk

changes -
- created crm14PrivacyNotice.njk
- amended customDisplay.njk

EMP-396 CRM14 - Complex page => Privacy Notice

---

server/@types/crm14/index.d.ts
server/controllers/crm/crm14Controller.ts
server/services/config/crm14DisplayConfig.json
server/views/components/customDisplay/crm14/crm14EvidencePart2.njk
server/views/components/customDisplay/customDisplay.njk
server/views/components/formTable.njk

Changes -
- added test api data to crm14Controller.ts
- amended customDisplay.njk
- amended formTable.njk
- added types for evidencePart2 to index.d.ts

Emp 393 crm 14 complex page evidence 2

---

server/views/components/customDisplay/crm15/crm15Income2.njk
server/views/components/customDisplay/crm15/crm15Outgoings.njk
server/views/components/customDisplay/crm15/crm15Savings.njk

- Fixed quotes in CRM 15 Income2 & Outgoings headings.
- Fix currency format for amount fields in CRM 15 Savings.

FIX: CRM15 headings

---

.github/deployments/deployment.yml

**Changes made**
- Added ENVIRONMENT_NAME env variable to deployment.yml

EMP-352: Configure Phase Banner

---

server/services/config/crm14DisplayConfig.json
server/utils/crmFieldFormatter.test.ts
server/utils/crmFieldTransformer.test.ts
server/utils/crmFieldTransformer.ts
server/utils/nunjucksSetup.ts
server/views/components/customDisplay/crm14/crm14Declarations.njk
server/views/components/customDisplay/crm14/crm14InterestsOfJustice.njk
server/views/components/customDisplay/crm14/crm14PrivacyNotice.njk
server/views/components/customDisplay/crm15/crm15Income1.njk
server/views/components/customDisplay/crm15/crm15Income2.njk
server/views/components/customDisplay/crm15/crm15LandProperty.njk
server/views/components/customDisplay/crm15/crm15Outgoings.njk
server/views/components/formField.njk

- Created transformValue nunjucks filter
- Transformed every field value in CRM15 Income2 & Outgoings 
- Fixed CRM14 display configuration
- Modified CRM14 interests of justice to use formFields

EMP-418: CRM15 Data issue

---

server/controllers/crm/crm5Controller.ts
server/controllers/crm/crm7Controller.ts
server/utils/crmBackLink.test.ts

amended crm5 and crm7 controllers

amended crm controllers

---

.github/deployments/deployment.yml
server/config.ts
server/data/api/crmApiClient.test.ts
server/data/api/crmApiClient.ts
server/data/api/sdsApiClient.test.ts
server/data/api/sdsApiClient.ts
server/utils/cacheProvider.test.ts
server/utils/cacheProvider.ts

- Added cache environment variables.
- Added crmApiCache to cacheProvider.
- Modified crmApiClient to use crmApiCache.
- Added unit tests.

EMP-315: Cache CRM API responses

---

assets/js/printButton.js
assets/scss/local.scss
server/views/components/printButton.njk
server/views/pages/crmDetails.njk
server/views/partials/layout.njk

changes - 
- created printButton.njk
- created printButton.js
- amended crmDetails.njk

Emp 409 fe feature add print functionality to crm summary

---

assets/scss/local.scss
server/routes/index.test.ts
server/views/pages/index.njk
server/views/pages/searchEform.njk

- Modify labels in index page and search form UI template.
- Modify css to hide download in print view.

FIX: Index page and search form labels

---

server/controllers/crm/crm14Controller.test.ts
server/controllers/crm/crm4Controller.test.ts
server/controllers/crm/crm5Controller.test.ts
server/controllers/crm/crm7Controller.test.ts
server/controllers/searchEformController.test.ts
server/controllers/searchEformController.ts
server/utils/crmBackLink.test.ts
server/utils/crmBackLink.ts
server/views/pages/searchEform.njk

Changes -
- added backlink to searchEform.njk
- amended crmBackLink.ts
- amended searchEformController.ts
- amended tests

EMP-426   FE <Feature> Add backlink to search page

---

server/@types/eqApi/index.d.ts
server/controllers/generateReportController.test.ts
server/controllers/generateReportController.ts
server/controllers/index.ts
server/data/api/crmReportApiClient.test.ts
server/data/api/crmReportApiClient.ts
server/data/index.ts
server/routes/index.ts
server/services/crmReportApiService.test.ts
server/services/crmReportApiService.ts
server/services/index.ts
server/views/pages/generateReport.njk

- WIP: EMP-414 - CRM4 reporting

EMP-414 - CRM4 reporting

---

assets/scss/local.scss

Changes - 
amended local.scss to fix word break issue

EMP-433   FE <Feature> : Fix CRM evidence section styling

---

server/@types/express/index.d.ts
server/controllers/searchEformController.test.ts
server/controllers/searchEformController.ts

Changes -
- amended searchEformController.ts and express/index.d.ts
- updated searchEformController.test.ts

EMP-437   FE <Feature> : Pagination missing after back link

---

server/utils/userProfileGroups.ts

changes - 
amended userProfileGroups.ts function

 EMP-435-crm-4-report-downloaded-message

---

server/services/config/crm4DisplayConfig.json

Added additional expenditure types

EMP-443 - Added additional expenditure type

---

assets/js/clearErrors.js
assets/js/triggerDownload.js
server/controllers/generateReportController.test.ts
server/controllers/generateReportController.ts
server/routes/index.test.ts
server/routes/index.ts
server/views/pages/generateReport.njk

changes - 
- amended generateReport.njk
- amended generateReportController.ts
- amended generateReportController.test.ts
- removed download from routes/index.ts
- amended index.test.ts
- deleted triggerDownload.js
- added clearErrors.js

Emp 449 remove success message from generate report page

---

server/views/components/formField.njk

- Removed extra percentage sign in formField.njk

EMP-466: Fix duplicate percentage symbol in CRM details

---

integration_tests/mockApis/data/crm5Response.ts
server/@types/crm5/index.d.ts
server/services/config/crm5DisplayConfig.json

Fixed `clientNfa` missing field in `crm5` response

EMP-457 - Defect Fix - Fixing clientNfa missing field in crm5 response

---

assets/scss/local.scss

EMP-467   FE: Fix line break issue on CRM detail pages

---

server/views/pages/searchEform.njk

Changes made:
- Fixed label in searchEform view template.

EMP-454: Fixed search form label

---

server/views/components/customDisplay/crm7/crm7ScheduleOfTime.njk

Defect Fix - CRM 7 fix missing fields in Schedule Of Time Spent

EMP-468 - CRM 7 fix missing fields in Schedule Of Time Spent

---

assets/js/generateReport.js

changes - 
amended generateReport.js

EMP-451   FE: Clear error summary only for successful report download

---

server/services/config/crm7DisplayConfig.json

- Fix typo in CRM 7 display config.

EMP-417: Fix Evidence typo

---

server/services/config/crm4DisplayConfig.json

Changes made:
- Fixed Expenditure details labels in crm4DisplayConfig.json

EMP-461: CRM 4 defects expenditure details page

---

server/utils/crmFieldFormatter.test.ts
server/utils/crmFieldFormatter.ts
server/views/pages/searchEform.njk

Defect Fix - Fixing UI side of it

EMP-458 - CRM 4 defect - Search for an eform records page - Results

---

server/utils/nunjucksSetup.ts
server/utils/utils.test.ts
server/utils/utils.ts
server/views/components/formField.njk

changes -
- added boolean filter to utils.ts
- amended nunjucksSetup.ts
- amended formField.njk

EMP-459 CRM 4 Defects - General Information Page

---

server/views/pages/crmDetails.njk

Changes - 
amended crm4OfficeUseOnly.njk to remove govuk-brand-colour class from solicitors-declaration subheading

EMP-486   CRM 5 Defects - Solicitors Declaration

---

server/utils/searchEformValidation.test.ts
server/utils/searchEformValidation.ts

Defect Fix
EMP-455 - CRM 4 Defects - Search for an eform records page

EMP-455 - CRM 4 Defects - Search for an eform records page

---

server/controllers/crm/crm14Controller.ts
server/services/config/crm14DisplayConfig.json
server/views/components/customDisplay/crm14/crm14OfficeUseOnly.njk
server/views/components/customDisplay/customDisplay.njk

changes - 
- created crm14OfficeUseOnly.njk
- amended customDisplay.njk

Emp 432 fe feature crm 14 15 official use section

---

server/services/config/crm5DisplayConfig.json
server/utils/crmFieldTransformer.test.ts
server/utils/crmFieldTransformer.ts
server/views/components/customDisplay/crm5/crm5CaseDetails.njk
server/views/components/customDisplay/customDisplay.njk
server/views/components/formFieldHeading.njk

- Fixed firmAddress in CRM5 display config
- Added custom display for Case details in CRM5 display config
- Added transform for levelOfWork
- Created crm5CaseDetails custom template

EMP-481: CRM 5 defects firm details page

---

server/@types/crmDisplay/index.d.ts
server/services/config/crm14DisplayConfig.json
server/utils/crmDisplayConfigValidation.ts
server/utils/crmFieldTransformer.test.ts
server/utils/crmFieldTransformer.ts

- Added missing fields to CRM14 display config
- Added yesNo transform to required fields
- Added unit tests

EMP-397: CRM 14 missing fields

---

server/services/config/crm7DisplayConfig.json

changes - 
amended crm7DisplayConfig.json

EMP-504-crm-7-defects-solicitor-details

---

server/services/config/crm5DisplayConfig.json

- Added Details of Application subsection in the CRM5 display config.

EMP-496: Fixed CRM5 details of work completed

---

server/services/config/crm5DisplayConfig.json
server/utils/crmFieldFormatter.test.ts
server/utils/crmFieldFormatter.ts
server/views/components/formField.njk

Changes - 
- amended crm5DisplayConfig.json
- amended time filter in crmFieldFormatter.ts
- amended formField.njk
- amended crmFieldFormatter.test.ts

EMP-497-crm-5-defects-costs

---

server/services/config/crm5DisplayConfig.json

changes - 
amended crm5DisplayConfig.json

EMP-498-crm-5-fe-defects-case-history

---

server/@types/crmDisplay/index.d.ts
server/services/config/crm14DisplayConfig.json
server/services/config/crm4DisplayConfig.json
server/services/config/crm5DisplayConfig.json
server/services/config/crm7DisplayConfig.json
server/utils/crmDisplayConfigValidation.ts
server/views/components/customDisplay/crm7/crm7NonStandardFeeClaim.njk
server/views/components/customDisplay/customDisplay.njk

- Removed redundant title for customDisplay in all display config and updated schema
- Updated crm display config validation
- Created custom display template for Non Standard Fee Claim

EMP-506: CRM7 defect reasons for non standard fee claim

---

server/services/config/crm7DisplayConfig.json

changes - 
amended crm7DisplayConfig.json

EMP-508-crm-7-defects-case-details

---

server/@types/crm5/index.d.ts
server/services/config/crm5DisplayConfig.json
server/services/crmDisplayService.test.ts
server/services/crmDisplayService.ts

- Added StandardProperties to crm5 type
- Added StandardProperties section to CRM5 display config
- Updated unit tests
- Updated crmDisplayService to return the first available section

EMP-528: CRM 5 Fix missing Standard Properties section

---

server/views/components/customDisplay/crm7/crm7ScheduleOfTime.njk

changes - 
amended crm7ScheduleOfTime.njk

Emp 510 crm 7 defects schedule of time

---

server/views/components/customDisplay/crm7/crm7ClaimForCosts.njk

changes - 
amended crm7ClaimForCosts.njk

Emp 511 crm 7 defects claim for cost

---

server/services/config/crm5DisplayConfig.json

- Updated label in CRM 5 display config.

EMP-484: CRM 5 defects - income details page

---

server/services/config/crm5DisplayConfig.json
server/views/components/customDisplay/crm5/crm5CapitalDetails.njk
server/views/components/customDisplay/customDisplay.njk

- Created custom display for CRM 5 Capital Details.

EMP-483: CRM 5 defects - capital details page

---

server/views/components/customDisplay/crm7/crm7Disbursements.njk
server/views/components/customDisplay/crm7/crm7OfficeUseOnly.njk

512 - CRM 7 Defects - Disbursement
515 - CRM 7 Defects - Official Use Page

EMP-512 and EMP-515 - Defect Fix

---

server/services/config/crm7DisplayConfig.json

- Fixed labels, mapping & formatting in CRM7 display config.

EMP-513: CRM7 Fix claims total page

---

assets/scss/local.scss
server/views/partials/header.njk

Changes
- amended header.njk
- added styling to local.scss

EMP-453-crm-4-defects-landing-page

---

server/views/components/customDisplay/crmEvidence.njk
server/views/components/customDisplay/customDisplay.njk
server/views/pages/crmDetails.njk

- Modified crmEvidence template to prefix CRM14 folder where fileKey is prefixed with "att_"

EMP-541: Fix CRM14 evidence download

---

server/views/components/customDisplay/crm5/crm5OfficeUseOnly.njk
server/views/components/customDisplay/crm7/crm7OfficeUseOnly.njk

changes - 
- amended crm7OfficeUseOnly.njk
- amended crm5OfficeUseOnly.njk

EMP-539-crm-7-defects-official-use-page

---

server/utils/generateReportValidation.test.ts
server/utils/generateReportValidation.ts
server/utils/searchEformValidation.ts

- Improved date validation and error messages in generateReportValidation.ts
- Updated unit tests

EMP-479: Reporting UI defects date validation notifications

---

server/services/config/crm4DisplayConfig.json
server/services/config/crm5DisplayConfig.json
server/views/components/customDisplay/crm4/crm4OfficeUseOnly.njk
server/views/components/formSubsection.njk

Changes - 
- amended crm4OfficeUseOnly.njk
- amended formSubsection.njk
- amended crm4DisplayConfig.json
- amended crm5DisplayConfig.json

EMP-537-crm-4-defect-official-use-page

---

server/@types/crm7/index.d.ts
server/services/config/crm7DisplayConfig.json

- Added claim properties section in crm7DisplayConfig.json
- Updated crm7 type.

EMP-522: Fix missing CRM7 Claim Properties

---

server/views/components/customDisplay/crmEvidence.njk

changes - 
- amended crm4Evidence.njk

EMP-502-crm-5-fe-defects-evidence

---

server/views/pages/generateReport.njk

- Fixed labels in generateReport.njk

EMP-529: Fix generate report page labels

---

server/@types/crm7/index.d.ts
server/services/config/crm7DisplayConfig.json

Changes made:
- Added Standard Properties section to crm7DisplayConfig.json.
- Updated crm7 type.

EMP-550: CRM 7 Standard Properties section

---

server/@types/crm4/index.d.ts
server/services/config/crm4DisplayConfig.json

- Added Standard Properties section to crm4DisplayConfig.json.
- Updated crm4 type.

EMP-551: CRM4 standard properties section

---

server/services/config/crm7DisplayConfig.json

Defect fix - CRM 7 case details

EMP-505 - Defect fix - CRM 7 case details

---

server/views/pages/searchEform.njk

Changes made:
- Fixed label in searchEform.njk

EMP-454: Fix Search form label

---

server/controllers/index.ts
server/controllers/staticPageController.test.ts
server/controllers/staticPageController.ts
server/routes/index.test.ts
server/routes/index.ts
server/views/pages/cookies.njk
server/views/partials/footer.njk

Changes - 
- created cookies.njk
- created staticPageController.ts
- added staticPageController.ts to controllers/index.ts 
- added staticPageController to routes/index.ts
- added cookies link to footer.njk

EMP-275-access-cookies

---

server/utils/crmFieldFormatter.test.ts
server/utils/crmFieldFormatter.ts
server/views/components/customDisplay/crm7/crm7ScheduleOfTime.njk

Changes made:
- Added LAA Adjustments table to crm7ScheduleOfTime.njk

EMP-559: Added missing CRM7 LAA Adjustments

---

server/@types/crm7/index.d.ts
server/views/components/customDisplay/crm7/crm7Disbursements.njk

- Fixed office column and added invoiceAttachments field in crm7Disbursements.njk

EMP-535: CRM 7 fix missing disbursements fields

---

server/controllers/crm/crm14Controller.ts
server/controllers/crm/crm4Controller.test.ts
server/controllers/crm/crm4Controller.ts
server/controllers/crm/crm5Controller.test.ts
server/controllers/crm/crm5Controller.ts
server/controllers/crm/crm7Controller.ts
server/controllers/generateReportController.ts
server/controllers/searchEformController.ts
server/utils/crmBackLink.test.ts
server/utils/crmBackLink.ts
server/views/pages/index.njk
server/views/partials/header.njk

Changes - 
- amended crmBackLink.ts
- amended crmBackLink.test.ts
- amended crm4Controller.test.ts
- amended crm5Controller.test.ts

EMP-561-urgent-user-testing-back-button-behaviour

---

server/services/config/crm14DisplayConfig.json

EMP-549-crm-14-defects-about-you-1

---

server/@types/crm4/index.d.ts
server/controllers/crm/crm4Controller.test.ts
server/routes/index.test.ts
server/services/config/crm4DisplayConfig.json

- Added missing Authority fields to crm4DisplayConfig.json.
- Updated crm4 type.

EMP-476: Fix missing CRM4 expenditure details fields

---

assets/scss/local.scss
server/views/pages/crmDetails.njk

changes - 
- amended crmDetails.njk

EMP-562-crm-4-5-7-14-defect-fix-table-to-print-issue

---

server/@types/crmDisplay/index.d.ts
server/utils/crmDisplayConfigValidation.ts
server/utils/crmFieldTransformer.ts
server/views/components/customDisplay/crm14/crm14InterestsOfJustice.njk

- Added offenceType to crmFieldTransformer.ts
- Fixed label and transformed offenceType in crm14InterestsOfJustice.njk

EMP-566: CRM14 Fix Interests Of Justice 1 defect

---

server/services/config/crm7DisplayConfig.json

EMP-560 - CRM 7 Defect - Claim Summary

EMP-560 - CRM 7 Defect - Claim Summary

---

server/services/config/crm14DisplayConfig.json

- Fixed label in crm14DisplayConfig.json

EMP-569: CRM 14 Defect - Evidence 1 

---

server/views/components/customDisplay/crm14/crm14EvidencePart2.njk

- Replaced evidence data table with repeated section in crm14EvideencePart2.njk

EMP-571: CRM 14 Defect - Evidence 2

---

server/utils/generateReportValidation.test.ts
server/utils/generateReportValidation.ts

- Modified date range validation to 1 week in generateReportValidation.ts

EMP-585: Change CRM14 Report date validation to 1 week

---

assets/scss/local.scss
server/views/pages/searchEform.njk

Changes - 
- amended searchEform.njk

EMP-573-fe-search-eform-fix-font-in-search-results-table

---

server/utils/generateReportValidation.test.ts
server/utils/generateReportValidation.ts

- Modified date range validation to 1 week in generateReportValidation.ts

EMP-567: Change CRM14 Report date validation to 1 month

---

server/@types/searchEform/index.d.ts
server/controllers/searchEformController.test.ts
server/controllers/searchEformController.ts
server/views/pages/searchEform.njk

changes - 
- amended searchEform.njk
- amended searchEformController.ts
- amended searchEformController.test.ts
- amended index.d.ts

EMP-596-adding-ufn-column-in-table

---

server/@types/crm14/index.d.ts
server/views/components/customDisplay/crm14/crm14Income.njk

- Fixed mapping for haveIncomeOverThreshold in crm14Income.njk

EMP-577: Fixed mapping for CRM14 Income section Q4

---

server/views/components/customDisplay/crm14/crm14Declarations.njk
server/views/components/customDisplay/crm14/crm14Income.njk
server/views/components/customDisplay/crm4/crm4OfficeUseOnly.njk
server/views/components/customDisplay/crm5/crm5OfficeUseOnly.njk
server/views/components/customDisplay/crm7/crm7OfficeUseOnly.njk

Changes made:-
- Added Declaration by the Partner section in crm14Declarations.njk
- Removed unused formFieldList imports.

EMP-600: Update CRM14 declaration to include partner section

---

server/views/components/customDisplay/crm4/crm4OfficeUseOnly.njk
server/views/components/customDisplay/crm7/crm7OfficeUseOnly.njk

Changes - 
- amended crm4OfficeUseOnly.njk
- amended crm7OfficeUseOnly.njk

EMP-538-crm-5-defects-official-use-page

---

server/@types/crm14/index.d.ts
server/utils/crmFieldTransformer.ts
server/views/components/customDisplay/crm14/crm14Income.njk

**Changes:**
- Updated labels, field mappings and transformed every fields in crm14Income.njk
- Updated crm14 type

EMP-578: CRM-14 Update income section amount fields

---

server/views/components/customDisplay/crm14/crm14AboutTheInformation.njk

changes - 
amended crm14AboutTheInformation.njk

EMP-605-crm-14-section-12-about-the-information-is-missing-data-for-disabilities

---

server/views/components/formField.njk

- Added formatHours in formField.njk

EMP-556: Add formatHours to formField component

---

server/views/components/customDisplay/crmEvidence.njk

- Remove apostrophe from filename in crmEvidence.njk

EMP-618: Strip apostrophe from filename

---

server/@types/crm14/index.d.ts
server/services/config/crm14DisplayConfig.json
server/views/components/customDisplay/crm14/crm14LegalRepresentation.njk
server/views/components/customDisplay/customDisplay.njk

Added missing fields
Created a new `crm14LegalRepresentation.njk` file
Added customDisplay for crm14LegalRepresentation

EMP-572 - CRM14 - Defect Fix - Legal REP

---

server/views/components/customDisplay/crm14/crm14Income.njk

changes - 
amended crm14Income.njk

Emp 570 crm 14 defects income

---

server/services/config/crm14DisplayConfig.json

- Added hideWhen condition to Evidence: 1 and Income section in crm14DisplayConfig.json.

EMP-615: CRM 14 - Conditional display of evidence 1 and income sections

---

server/views/components/customDisplay/crm15/crm15Income2.njk

- Remove default frequency - '1 week' in crm15Income2.njk

EMP-587: CRM15 - Remove default frequency from Income section

---

server/views/components/customDisplay/crm14/crm14LegalRepUse.njk

EMP-616 - Defect fix - format date

---

server/services/config/crm14DisplayConfig.json

changes - 
amended crm14DisplayConfig.json

EMP-575-crm-14-fe-about-your-partner-section-showing-but-client-does-not-have-a-partner

---

server/views/components/customDisplay/crm15/crm15Income2.njk

- Fixed typo on partnerMaintenancePaymentPaidEvery field in crm15Income2.njk

EMP-623: CRM15 income - fix missing frequency

---

server/views/components/customDisplay/crm15/crm15Outgoings.njk

- Added heading in crm15Outgoings.njk

EMP-588: CRM 15 Outgoings - fix missing text

---

server/views/components/customDisplay/crm15/crm15Income2.njk

- Updated field mappings in crm15Income2.njk

EMP-631: Update field mappings

---

server/views/components/customDisplay/crm14/crm14OfficeUseOnly.njk

changes - 
amended crm14OfficeUseOnly.njk

Emp 579 crm 14 office use section funding decision section field labels do not match in the fe

---

server/views/components/customDisplay/crm15/crm15Savings.njk

changes - 
amended crm15Savings.njk

EMP-617-crm-15-fe-savings-bank-accounts-overdrawn-new-system-shows-false-display-no-instead

---

server/@types/crm14/index.d.ts
server/@types/crm15/index.d.ts
server/controllers/crm/crm14Controller.test.ts
server/routes/index.test.ts
server/views/components/customDisplay/crm15/crm15Income1.njk

Changes made:
- Created crm15 type
- Updated layout of employers and businesses in crm15Income1.njk
- Updated unit tests

EMP-628: Updated layout of CRM15 Income 1

---

server/views/components/customDisplay/crm15/crm15Income2.njk

- Removed text from crm15Income2.njk

EMP-642: CRM15 Income 2 - erroneous text appearing

---

server/views/components/customDisplay/crm14/crm14EvidencePart2.njk

- Updated PSE and added Process message section in crm14EvidencePart2.njk

EMP-625: CRM14 PSE section

---

server/views/pages/contactUs.njk

EMP-277:  Update contact us page

---

server/views/components/customDisplay/crm14/crm14EvidencePart2.njk

Reverts ministryofjustice/laa-crime-equinity-historical-data-frontend#359

Revert "EMP-625: Update heading in crm14 evidence 2"

---

server/services/config/crm14DisplayConfig.json

EMP-637-crm-14-15-about-you-2-section-we-need-to-show-date-of-separation-if-separated-is-selected

---

server/views/components/customDisplay/crm15/crm15Savings.njk

Changes - 
- amended crm15Savings.njk

EMP-635-crm-14-15-defects-crm-15-savings

---

server/views/components/customDisplay/crm15/crm15Income2.njk

Changes - 
amended crm14Income2.njk

EMP-629-crm-14-15-fe-defects-income-2-page

---

server/views/components/customDisplay/crm14/crm14LegalRepresentation.njk

EMP-640 - Legal rep Additional scenario

EMP-640 - Legal rep Additional scenario

---

server/views/components/customDisplay/crmEvidence.njk

chganges - 
amended crmEvidence.njk

EMP-648-crm-14-fe-processed-unprocessed-evidence-separation

---

assets/scss/local.scss
server/views/components/customDisplay/crm15/crm15Savings.njk

Changes - 
- amended crm15Savings.njk

EMP-632-fe-crm-15-balance-column-formatting-incorrect-for-minus-values

---

server/services/config/crm14DisplayConfig.json
server/views/components/customDisplay/crm14/crm14AboutTheInformation.njk
server/views/components/customDisplay/crm14/crm14Evidence1.njk
server/views/components/customDisplay/crm14/crm14Evidence2.njk
server/views/components/customDisplay/crm14/crm14Income.njk
server/views/components/customDisplay/crm14/crm14InterestsOfJustice1.njk
server/views/components/customDisplay/customDisplay.njk
server/views/pages/searchEform.njk

Changes made:-
- Added custom display config & template CRM14 Evidence 1.
- Cleaned up == to ===
- Refactored template names - crm14InterestsOfJustice1, crm14Evidence2

EMP-576: CRM14 Evidence 1 - Fix conditional display

---

server/views/components/navigationBar.njk

Changes - 
amended navigationBar.njk

EMP-662-accessibility-e-form-details-page-1-add-govuk-link-classes-to-links-to-ensure-focus-is-retained-on-the-links

---

server/views/components/pagination.njk
server/views/pages/searchEform.njk

- Modified to only show pagination when no. of pages > 1 in pagination.njk

EMP-657: Accessibility - pagination not required on search results of 1 page

---

assets/scss/local.scss
server/controllers/searchEformController.test.ts
server/utils/searchEformValidation.test.ts
server/utils/searchEformValidation.ts
server/views/components/searchEformBox.njk

Changes - 
- amended searchEformBox.njk
- amended searchEformValidation.ts
- amended searchEformController.test.ts
- amended searchEformValidation.test.ts

EMP-659-accessibility-search-criteria-page-3-consider-reducing-the-size-of-the-three-search-boxes-at-the-top-form-error-required

---

integration_tests/e2e/crm5/crm5.feature
integration_tests/e2e/crm5/crm5.ts
integration_tests/mockApis/eqApi.ts

- Fixed typo in eqApi.ts
- Update CRM5 test and feature file

EMP-261: Fixed CRM 5 BDD test

---

server/views/components/searchEformBox.njk

Changes - 
- amended searchEformBox.njk

EMP-658-accessibility-search-criteria-page-2-potentially-separate-out-usn-on-the-search-page-as-field-on-its-own

---

.github/workflows/action.yml

- Removed deploy-staging job from GitHub workflow.

EMP-706: Remove staging from github deploy workflow

---

server/views/pages/contactUs.njk
server/views/pages/cookies.njk
server/views/pages/crmDetails.njk
server/views/pages/generateReport.njk
server/views/pages/index.njk
server/views/pages/searchEform.njk

Changes - 
- amended contactUs.njk
- amended cookies.njk
- amended crmDetails.njk
- amended generateReport.njk
- amended index.njk
- amended searchEform.njk

EMP-709-duplicate-main-landmarks

---

package-lock.json
package.json
server/middleware/setUpHealthChecks.ts

Changes made:
Upgraded `express`,  `express-prom-bundle`, `express-session` dependencies to fix Cookie lib issue.

EMP-718: Fix Snyk cookie xss lib issue

---

server/views/components/customDisplay/crmEvidence.njk
server/views/components/customDisplay/crmFurtherInformation.njk

Changes - 
- amended crmEvidence.njk
- amended crmFurtherInformation.njk

Emp 716 download link does not have hidden text

---

server/views/pages/accessibilityStatement.njk
server/views/pages/contactUs.njk
server/views/pages/cookies.njk
server/views/pages/crmDetails.njk
server/views/pages/error.njk
server/views/pages/generateReport.njk
server/views/pages/index.njk
server/views/pages/searchEform.njk

Changes - 
- amended accessibilityStatement.njk
- amended contactUs.njk
- amended cookies.njk
- amended crmDetails.njk
- amended error.njk
- amended generateReport.njk
- amended index.njk
- amended searchEform.njk

EMP-708-page-title-and-h-1-issues

---

server/app.ts
server/monitoring/metricsApp.ts
server/routes/testutils/appSetup.ts

Applied recommended fix to disable X-Powered-By header for Express app

EMP-718: Fix Snyk information exposure issue

---

server/controllers/searchEformController.test.ts
server/controllers/searchEformController.ts
server/routes/index.test.ts
server/utils/searchEformValidation.test.ts
server/utils/searchEformValidation.ts
server/views/components/searchEformBox.njk

Changes made:
- Modified searchEformController to add clientDOB field to form submission
- Added clientDOB field to searchEform.njk
- Updated unit tests

EMP-704: Add clientDOB field to search page

---

.github/deployments/service.yml
helm_deploy/laa-crime-equinity-historical-data-frontend/Chart.yaml
helm_deploy/laa-crime-equinity-historical-data-frontend/templates/_environment.tpl
helm_deploy/laa-crime-equinity-historical-data-frontend/templates/_helpers.tpl
helm_deploy/laa-crime-equinity-historical-data-frontend/templates/deployment.yaml
helm_deploy/laa-crime-equinity-historical-data-frontend/templates/ingress.yaml
helm_deploy/laa-crime-equinity-historical-data-frontend/templates/service.yaml
helm_deploy/laa-crime-equinity-historical-data-frontend/values-dev.yaml
helm_deploy/laa-crime-equinity-historical-data-frontend/values-prod.yaml
helm_deploy/laa-crime-equinity-historical-data-frontend/values-uat.yaml
helm_deploy/laa-crime-equinity-historical-data-frontend/values.yaml
helm_deploy/values.yaml

- Added helm deploy configuration files.

EMP-692: Initial helm deploy setup

---

.github/workflows/_deploy-to.yml
.github/workflows/action.yml
helm_deploy/laa-crime-equinity-historical-data-frontend/values-archive.yaml

- Refactored helm deploy config files.

EMP-692: Refactored helm deploy config

---

.github/workflows/action.yml

EMP-692: update deployment to only use sub-workflow instead of steps in order to support secrets inheritance

EMP-692: update deployment to only use sub-workflow instead of steps in order to support secrets inheritance

---

.github/workflows/action.yml

EMP-692: Remove references to env variables for hardodded string value

EMP-692: Remove references to env variables for harcodded string value

---

kubernetes/helm_deploy/laa-crime-equinity-historical-data-frontend/templates/_helpers.tpl
kubernetes/helm_deploy/laa-crime-equinity-historical-data-frontend/templates/deployment.yaml
kubernetes/helm_deploy/laa-crime-equinity-historical-data-frontend/values.yaml

EMP-692: add helm helper values for deployment templates

EMP-692: add helm helper values for deployment templates

---

kubernetes/helm_deploy/laa-crime-equinity-historical-data-frontend/values.yaml

EMP-692: Fixed indent error on container specs configuration

EMP-692: Fixed indent error on container specs configuration

---

kubernetes/helm_deploy/laa-crime-equinity-historical-data-frontend/templates/service.yaml

EMP-692: fixed reference to selectorLabels on service.selector

EMP-692: fixed reference to selectorLabels on service.selector

---

kubernetes/helm_deploy/laa-crime-equinity-historical-data-frontend/values.yaml

EMP-629: change ingress class name to ngix to match annotations value

EMP-629: change ingress class name to ngix to match annotations value

---

.github/workflows/action.yml

EMP-692: Fixed image name and tag to have a prefix name before sha

EMP-692: Fixed image name and tag to have a prefix name before sha

---

assets/scss/local.scss
server/views/components/searchEformBox.njk

Changes - 
- amended searchEformBox.njk

EMP-720-fe-update-layout-for-tablet-view

---

server/views/components/customDisplay/crm15/crm15LandProperty.njk

changes - 
- amended crm15LandProperty.njk

EMP-689-crm-14-15-fe-defects-land-property-phase-2-re-design

---

kubernetes/helm_deploy/laa-crime-equinity-historical-data-frontend/templates/_environment.tpl

**Changes:**
Reinstated `ENVIRONMENT_NAME` env var in helm environment template.

EMP-730: Fix local label showing in all environments

---

server/config.ts

**Changes:**
- Fix environment variable names in config.ts

EMP-729: Fix config to use new env vars

---

kubernetes/helm_deploy/laa-crime-equinity-historical-data-frontend/values-uat.yaml

Changes made:
Fix SSO_REDIRECT_URI in values-uat.yml

EMP-729: Fix values-uat.yml

---

kubernetes/helm_deploy/laa-crime-equinity-historical-data-frontend/templates/_environment.tpl

**Changes made:** 
- Modified deployment environment variables to retrieve application secrets from `equinity-historical-data-frontend-secrets` kubernetes secret.

EMP-729: Switch to new kubernetes secrets 

---

.github/workflows/action.yml

- Updated github workflow to included integration tests and to use latest hmpps-template-typescript scripts.

EMP-731: Updated github workflow to include integration tests

---

.github/workflows/action.yml

- Fixed node_unit_tests pipeline job in github workflow action.

EMP-731: Fix node_unit_tests pipeline job

---

.github/workflows/action.yml

- Updated job names in github workflow.

EMP-731: Updated job names in github workflow

---

integration_tests/e2e/crm14/crm14.feature
integration_tests/e2e/crm4/crm4.feature
integration_tests/e2e/crm5/crm5.feature

Changes - 
- amended crm4.feature
- amended crm5.feature
- amended crm14.feature

EMP-743-fe-fix-bdd-test-failures-for-crm-4-crm-5-and-crm-14

---

server/services/crmDisplayService.ts
server/utils/conditionalDisplayHelper.test.ts
server/utils/conditionalDisplayHelper.ts
server/utils/crmDisplayHelper.test.ts
server/utils/crmDisplayHelper.ts
server/utils/crmFieldHelper.test.ts
server/utils/crmFieldHelper.ts
server/utils/utils.test.ts
server/utils/utils.ts

- Moved conditional display logic to conditionalDisplayHelper.ts
- Moved fieldHasValue and getCrmFieldValue functions to crmFieldHelper.ts
- Updated tests

EMP-745: Refactor CRM Display Helper

---

server/views/components/customDisplay/crmEvidence.njk

changes - 
amended crmEvidence.njk

EMP-755-urgent-issue-affecting-all-downloads

---

kubernetes/helm_deploy/laa-crime-equinity-historical-data-frontend/templates/_environment.tpl
kubernetes/helm_deploy/laa-crime-equinity-historical-data-frontend/values-uat.yaml
kubernetes/helm_deploy/laa-crime-equinity-historical-data-frontend/values.yaml

- Added `SSO_DISABLED` environment variable to _environment.pl
- Set `SSO_DISABLED` = false in default values.yaml
- Set `SSO_DISABLED` = true in default values_uat.yaml

EMP-757: Added SSO_DISABLED env var to helm config

---

assets/js/generateReport.js
server/controllers/generateReportController.ts
server/data/api/crmReportApiClient.test.ts
server/data/api/crmReportApiClient.ts
server/services/generateReportService.test.ts
server/services/generateReportService.ts
server/utils/generateReportValidation.test.ts
server/utils/generateReportValidation.ts

Changes - 
- amended crmReportApiClient.ts
- amended generateReportService.ts
- amended generateReportController.ts
- amended generateReportService.test.ts
- amended generateReport.js

Emp 740 fe add crm 14 provider report functionality

---

server/controllers/generateReportController.test.ts
server/controllers/generateReportController.ts
server/utils/generateReportHelper.test.ts
server/utils/generateReportHelper.ts

Changes made:
- Moved `buildReportRequest` and `getReportParams` functions to separate file - generateReportHelper.ts
- Added unit tests.

EMP-759: Refactor Generate report controller

---

server/controllers/homeController.test.ts
server/controllers/homeController.ts
server/routes/index.test.ts
server/routes/index.ts
server/utils/userProfileGroups.test.ts
server/utils/userProfileGroups.ts
server/views/pages/index.njk

changes - 
- amended homeController.ts
- amended homeController.test.ts
- amended index.njk
- amended index.ts
- amended userProfileGroups.ts
- amended userProfileGroups.test.ts

EMP-735-fe-restrict-access-to-crm-4-provider-report

---

server/utils/generateReportValidation.test.ts
server/utils/generateReportValidation.ts
server/utils/searchEformValidation.test.ts
server/utils/searchEformValidation.ts

Changes - 
- amended generateReportValidation.ts
- amended generateReportValidation.test.ts

EMP-761-fe-apply-validation-to-date-from-fields

---

server/views/pages/accessibilityStatement.njk

Changes - 
- amended accessibilityStatement.njk

EMP-748-update-accessibility-statement-to-remove-known-issues-section

---

server/utils/generateReportValidation.test.ts
server/utils/generateReportValidation.ts
server/utils/searchEformValidation.test.ts
server/utils/searchEformValidation.ts

Changes - 
- amended generateReportValidation.ts
- amended generateReportValidation.test.ts
- amended searchEformValidation.ts
- amended searchEformValidation.test.ts

EMP-764-fe-implement-environment-based-7-year-validation-rule

---

server/controllers/homeController.test.ts
server/controllers/homeController.ts
server/views/pages/index.njk

Changes -
- amended homeController.ts
- amended homeController.test.ts
- amended index.njk

EMP-767-fe-hide-reporting-links-on-homepage-in-the-archive-fe-environment

---

server/controllers/homeController.test.ts
server/controllers/homeController.ts
server/routes/index.test.ts
server/utils/userProfileGroups.test.ts
server/utils/userProfileGroups.ts
server/views/pages/index.njk

Changes made:
- Added isViewEformAllowed to userProfileGroups.ts to check if the user has been assigned to a CRM user group.
- Modified index view to use isViewEformAllowed to determine which links should be available.
- Added unit tests

EMP-777: Add isViewEformAllowed access control

---

server/controllers/homeController.test.ts

Changes made:
- Fixed lint error in unit test.

EMP-777: Fixed lint error
